### PR TITLE
MQB - Forza Motorsport 2023

### PR DESCRIPTION
**Pull request by aslobodskoy**
Added support of Forza M 2023 to MQB sketch.

### CODE REVIEW

**Comment by r00li** [comment]
Will have a look at what changed here. But at the first glance it looks like this could be solved easier. Because as far as I can see none of the addresses for the properties that we need have changed. But I need to look a bit deeper.

**Comment by aslobodskoy** [comment]
Speed, Gear & Packet size has been changed

**Comment by r00li** [comment]
Hi!
Thank you for the contribution. Sorry it took this long for me to finally get to it. Due to the fact that the code has been changed a lot since you made the PR, I implement your changes on my own. Here is the commit: https://github.com/r00li/CarCluster/commit/28cca598dd50fd54a90aaf22d5c178154e615315

If you have the time I would ask you to maybe test the new code to see if everything works correctly.

**Comment by r00li** [comment]
Well, I am gonna assume everything works. Closing this.

**Pull request closed without merging**
